### ISSUE TITLE
Cannot find -lc -lm 

### ISSUE THREAD

**Issue by maciektr** [sio2project/sio2jail#13]
I'm trying to install sio2jail on fedora 28. I'm getting stuck on "[ 77%] Linking C executable leak-tiny_32" followed by
"/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status"
As far as I'm concerned I've got the standard libs. Can I kindly ask for help with that?

**Comment by Michcioperz** [comment]
I can't say I'm familiar with Fedora, but do you have the 32-bit versions of the standard libs? `leak-tiny_32` is built with `-m32` flag.

**Comment by Michcioperz** [comment]
I familiarized myself a little with Fedora using Docker just now.

 - `cannot find -lc` during scdoc compilation can be resolved by installing `glibc-static`,
 - `cannot find -lstdc++` during sio2jail compilation can be resolved by installing `libstdc++-static`,
 - and finally, your error can be resolved by installing `glibc-static.i686`, but afterwards you'll probably be missing `libstdc++-static.i686`, which needs to be installed for target `sum_cxx`.

**Comment by Michcioperz** [comment]
So, I believe the problem here is that everything we build for sio2jail, we link statically in order to cut down on runtime dependencies.

**Comment by maciektr** [comment]
Worked for me, thanks a lot :)
