### ISSUE TITLE
CMake does not check for needed dependencies during configuration

### ISSUE THREAD

**Issue by Michcioperz** [sio2project/sio2jail#5]
`mkdir build; cd build; cmake ..` proceeds perfectly well on a system without libseccomp-dev and libtclap-dev. I think CMake should get to yell about this during config and not during build.

**Comment by Wolf480pl** [comment]
We download and build libseccomp on our own, during the build process. Not sure about libtclap.

**Comment by Michcioperz** [comment]
libseccomp-dev is still needed. Telling CMake to link target to library only makes it add `-llibrary`, it doesn't do anything to ensure the headers are there.
libcap-dev is also part of the problem.

**Comment by teqwve** [comment]
AFAIK libseccomp should worked at the time. Nevertheless, in v1.1.1, we've introduced some changes in build system that address Your issues.
