### ISSUE TITLE
Add nice output format

### ISSUE THREAD

**Issue by Michcioperz** [sio2project/sio2jail#8]
First step to making it usable without oiejq

**Comment by accek** [comment]
What is oiejq?

**Comment by Michcioperz** [comment]
s2j wrapping bash script Wolf wrote for contestants that runs user specified program in just-count-time-and-skip-all-other-s2j-features mode and prints results in a human readable manner
What I meant is it might be a good idea to just add a nicer output format

**Comment by accek** [comment]
I like this cool name. :)
